spring:
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true  # DB 초기화(data.sql)를 Hibernate 이후로 미룸
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 6000

logging:
  level:
    root: INFO
    io.lettuce.core: INFO
    org.springframework.data.redis: INFO
    org.hibernate.SQL: INFO             # Hibernate SQL 쿼리 로깅
    org.hibernate.stat: OFF             # Hibernate 통계 로깅
    org.hibernate.orm.jdbc.bind: OFF    # 바인딩된 값 로깅

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    authorization-grant-type: authorization_code

redis:
  registration-token:
    minutes: ${REDIS_REGISTRATION_TOKEN_EXPIRATION_MINUTES}
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_EXPIRATION_TIME}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_TIME}

ai:
  server:
    base-url: ${AI_SERVER_BASE_URL} # AI 서버의 기본 URL

management:
  endpoint:
    health:
      show-details: always  # /actuator/health 접속 시 상세 정보(Redis 상태 포함) 항상 표시
  health:
    redis:
      enabled: true         # Redis Health Indicator 활성화 (기본값)

fcm:
  config:
    path: classpath:firebase-admin-sdk.json   # resources 폴더 기준

apple:
  bundle-id: com.jebiyeon.familyfront # iOS 개발자에게 물어봐서 정확한 Bundle ID 입력